version: '3.5'

services:
    mapper-php:
        container_name: mapper-php
        build:
            context: docker
            dockerfile: php-cli/Dockerfile
        networks:
          - analytics
        volumes:
          - ./:/mapper
        external_links:
          - analytics-clickhouse
networks:
    analytics:
        external: true
        name: analytics
        driver: bridge